import React from "react";
import { Label } from "@/components/ui/label";

const formats = [
  { id: "league", title: "League", desc: "Everyone plays home and away." },
  { id: "round_robin", title: "Round Robin", desc: "Everyone plays each other once." },
  { id: "knockout", title: "Knockout", desc: "Single elimination bracket." },
  { id: "group_stage_knockout", title: "Group + Knockout", desc: "Groups first, then qualifying teams enter a knockout bracket." },
  { id: "double_elimination", title: "Double Elimination", desc: "Two lives per team." },
  { id: "swiss", title: "Swiss", desc: "Paired by results each round." },
];

const visibilities = [
  { id: "public", title: "Public" },
  { id: "private", title: "Private" },
  { id: "invite_only", title: "Invite only" },
];

export default function FormatStep({ data, set }) {
  return (
    <div className="space-y-6">
      <div>
        <Label>Tournament format</Label>
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          {formats.map((f) => (
            <button key={f.id} type="button" onClick={() => set({ format: f.id })}
              className={`rounded-2xl border p-4 text-left transition-all ${data.format === f.id ? "border-foreground bg-accent/60" : "border-border/60 hover:bg-accent/30"}`}>
              <div className="font-medium">{f.title}</div>
              <div className="text-sm text-muted-foreground">{f.desc}</div>
            </button>
          ))}
        </div>
      </div>
      {data.format === "group_stage_knockout" && (
        <div className="grid gap-4 rounded-2xl border border-border/60 bg-muted/30 p-4 sm:grid-cols-2">
          <label className="text-sm font-medium">Number of groups
            <input type="number" min="2" value={data.group_count} onChange={(event) => set({ group_count: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-2" />
          </label>
          <label className="text-sm font-medium">Teams qualifying per group
            <input type="number" min="1" value={data.qualifiers_per_group} onChange={(event) => set({ qualifiers_per_group: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-2" />
          </label>
          <p className="sm:col-span-2 text-xs text-muted-foreground">The total qualifiers must form a knockout bracket (4, 8, 16, …). Teams are assigned and group fixtures generated by the shared API after team setup.</p>
        </div>
      )}
      <div>
        <Label>Participation</Label>
        <div className="mt-3 flex flex-wrap gap-2">
          {visibilities.map((v) => (
            <button key={v.id} type="button" onClick={() => set({ visibility: v.id })}
              className={`rounded-full border px-4 py-1.5 text-sm transition-colors ${data.visibility === v.id ? "border-transparent bg-foreground text-background" : "border-border/60 text-muted-foreground hover:text-foreground"}`}>{v.title}</button>
          ))}
        </div>
      </div>
    </div>
  );
}
