const tokenKey = 'tournament_local_token';
const urlToken = new URLSearchParams(window.location.search).get('access_token');
if (urlToken) { localStorage.setItem(tokenKey, urlToken); window.history.replaceState({}, document.title, window.location.pathname + window.location.hash); }
const token = () => localStorage.getItem(tokenKey) || sessionStorage.getItem(tokenKey);
const request = async (url, options = {}) => {
  const response = await fetch(url, { ...options, headers: { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(token() ? { Authorization: `Bearer ${token()}` } : {}), ...options.headers } });
  const data = response.status === 204 ? null : await response.json().catch(() => null);
  if (!response.ok) { const error = new Error(data?.error || 'Request failed'); error.response = { status: response.status, data }; throw error; }
  return data;
};
const entity = (name) => ({ list: (sort = 'created_date', limit = 100) => request(`/api/entities/${name}?sort=${encodeURIComponent(sort)}&limit=${limit}`), filter: (filter = {}, sort = 'created_date', limit = 100) => request(`/api/entities/${name}?filter=${encodeURIComponent(JSON.stringify(filter))}&sort=${encodeURIComponent(sort)}&limit=${limit}`), get: (id) => request(`/api/entities/${name}/${id}`), create: (data) => request(`/api/entities/${name}`, { method: 'POST', body: JSON.stringify(data) }), bulkCreate: (items) => request(`/api/entities/${name}/bulk`, { method: 'POST', body: JSON.stringify({ items }) }), update: (id, data) => request(`/api/entities/${name}/${id}`, { method: 'PATCH', body: JSON.stringify(data) }), delete: (id) => request(`/api/entities/${name}/${id}`, { method: 'DELETE' }), deleteMany: (filter = {}) => request(`/api/entities/${name}?filter=${encodeURIComponent(JSON.stringify(filter))}`, { method: 'DELETE' }) });
const auth = { isAuthenticated: async () => !!(await auth.me()), me: () => request('/api/auth/me'), loginViaEmailPassword: async (email, password, remember = true) => { const result = await request('/api/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); (remember ? localStorage : sessionStorage).setItem(tokenKey, result.access_token); return result.user; }, register: async ({ email, password, full_name }) => { const result = await request('/api/auth/register', { method: 'POST', body: JSON.stringify({ email, password, full_name }) }); localStorage.setItem(tokenKey, result.access_token); return result; }, logout: (redirect) => { localStorage.removeItem(tokenKey); sessionStorage.removeItem(tokenKey); if (redirect !== false) window.location.href = typeof redirect === 'string' ? redirect : '/'; }, redirectToLogin: () => { window.location.href = '/login'; }, setToken: (value) => localStorage.setItem(tokenKey, value), verifyOtp: async () => ({ access_token: token() }), resendOtp: async () => ({ ok: true }), resetPasswordRequest: (email) => request('/api/auth/reset-request', { method: 'POST', body: JSON.stringify({ email }) }), resetPassword: (data) => request('/api/auth/reset', { method: 'POST', body: JSON.stringify(data) }), loginWithProvider: () => { window.location.href = '/api/auth/google'; } };
const db = { auth, entities: new Proxy({}, { get: (_target, name) => entity(name) }), functions: { invoke: async (name, data) => ({ data: await request(`/api/functions/${name}`, { method: 'POST', body: JSON.stringify(data) }) }) }, integrations: { Core: { UploadFile: async ({ file }) => { const body = new FormData(); body.append('file', file); return request('/api/uploads', { method: 'POST', body }); } } } };
globalThis.__LOCAL_DB__ = db;
export { db }; export default db;
